/// design/169 — allowlisted evidence kinds (mirror of server evidence_kinds.py).
library;

const Set<String> kEvidenceAllowedKinds = {
  // lifecycle / decision
  'client_session_start',
  'client_session_end',
  'pref_translate_set',
  'pref_translate_read',
  'pref_shadowing_set',
  'nav_tab',
  'reader_open',
  'reader_cursor',
  'figure_window_req',
  'figure_window_res',
  'ingest_upload_start',
  'ingest_poll_tick',
  'reanalyze_start',
  'reanalyze_pref_snapshot',
  // error / consistency
  'client_api_fail',
  'client_api_timeout',
  'client_unhandled',
  'client_hang',
  'client_silent_catch',
  'translate_poll_exhausted',
  'server_handler_fail',
  'server_job_terminal_error',
  'figure_preserve_miss',
  'figure_meta_write',
  'figure_meta_regress',
  'figure_preserve_skip',
  'ingest_integrity_violation',
  'stall_skipped_live_worker',
  'stall_fired',
  'figure_window_empty',
  'figure_blob_miss',
  // design/169c — dense translate / open / poll
  'translate_phase_enter',
  'translate_item_done',
  'translate_call_fail',
  'translate_call_slow',
  'translate_call_start',
  'translate_call_done',
  'translate_phase_exit',
  'translate_save_ko',
  'open_ko_summary',
  'translate_poll_start',
  'translate_poll_ko',
  'translate_local_backfill_start',
  'translate_local_backfill_done',
  'translate_local_backfill_fail',
  // design/169g — causal handoff (phase 2)
  'handoff',
  'progress_view',
  // design/169h — interior checkpoint densify
  'checkpoint',
  // design/169i — artifact transfer ledger
  'artifact_observe',
  'artifact_transfer',
  'artifact_derive',
  'artifact_invalidate',
  // design/169d — full-product dense sensors
  'library_refresh',
  'library_count',
  'paper_delete',
  'ingest_cancel',
  'cache_save_sample',
  'reclaim_seed',
  'download_cache_fail',
  'papers_upload_fail',
  'library_list_miss',
  'papers_supersede_gc',
  'papers_delete_residual',
  'papers_gcs_orphan_sample',
  // design/177 — paper delete causal densify
  'paper_delete_start',
  'paper_delete_done',
  'paper_delete_conflict',
  'papers_residual_kinds',
  'figures_prior_pull',
  // design/169m — lease / sweeper causality
  'lease_heartbeat',
  'sweep_decision',
  'reclaim_attempt',
  // design/169n — library figure hydrate
  'figure_hydrate_start',
  'figure_hydrate_progress',
  'figure_hydrate_done',
  'figure_hydrate_partial',
  'figure_hydrate_abort',
  // design/169o — post-ingest harmonize residual
  'harmonize_residual_start',
  'harmonize_residual_progress',
  'harmonize_residual_done',
  'harmonize_residual_partial',
  'harmonize_residual_abort',
  // design/169p — shadowing practice prep evidence
  'shadowing_gate',
  'shadowing_ensure_start',
  'shadowing_ensure_done',
  'shadowing_plan_local_save',
  'post_handoff_enrich_done',
  'post_handoff_enrich_start',
  'pending_enrich_enqueue',
  'pending_enrich_scan',
  'pending_enrich_start',
  'pending_enrich_done',
  'pending_enrich_retry',
  'pending_enrich_give_up',
  'shadowing_boot_start',
  'shadowing_boot_done',
  'shadowing_build_round',
  'shadowing_loop_event',
  'shadowing_chunks_get',
  'shadowing_chunks_build_start',
  'shadowing_chunks_build_done',
  'shadowing_gemini_call_start',
  'shadowing_gemini_call_done',
  'shadowing_ingest_stage',
  'shadowing_ensure_join',
  'shadowing_ensure_wait_other',
  'shadowing_ensure_get',
  'shadowing_ensure_skip_ok',
  'shadowing_ensure_slice_start',
  'shadowing_ensure_slice_done',
  'shadowing_ensure_progress',
  'shadowing_ensure_timeout_continue',
  'shadowing_plan_resume',
  'shadowing_plan_save',
  'shadowing_plan_race',
  'shadowing_plan_regress',
  // design/176 — focus practice speaking clock
  'focus_session_start',
  'focus_session_end',
  'focus_block_done',
  'focus_day_success',
  // design/208
  'practice_grooming_decision',
  // design/209
  // design/209 KILLED — practice_cycle_wide / practice_evidence_flush
  // design/178 — worker wake causal densify
  'worker_wake_start',
  'worker_wake_done',
  'worker_config_mismatch',
  // design/179 — false worker_lost + poll/library
  'sweep_kill_decision',
  'ingest_poll_terminal',
  // design/180 — figure hydrate reliability
  'figure_png_req',
  'figure_png_done',
  'ingest_artifact_deleted',
  'ingest_artifact_purge_tick',
  'paper_handoff_start',
  'paper_handoff_done',
  'paper_cloud_wipe',
  'paper_upload_refused_acked',
  'transfer_pack_create',
  'transfer_pack_complete',
  'transfer_pack_download',
  'transfer_pack_deleted',
  'transfer_pack_purge_tick',
  'paper_handoff_abandoned',
  'paper_handoff_abandon_purge_tick',
  'paper_bulk_handoff_start',
  'paper_bulk_handoff_done',
  // design/187 — user artifacts device SoT
  'bookmarks_local_migrate_start',
  'bookmarks_local_migrate_done',
  'bookmarks_cloud_wipe',
  'bookmarks_sync_refused',
  'annotations_local_migrate_start',
  'annotations_local_migrate_done',
  'annotations_cloud_wipe',
  'annotations_sync_refused',
  'shadowing_local_migrate_start',
  'shadowing_local_migrate_done',
  'shadowing_cloud_wipe',
  'shadowing_sync_refused',
  'notes_local_migrate_start',
  'notes_local_migrate_done',
  'notes_cloud_wipe',
  'notes_sync_refused',
};
