# -*- coding: utf-8 -*-
"""Access gate: random OTP-style invite codes + admin allow/deny (design/67).

Codes look like TqG3-V12T — generated by the server (admin never invents them).
Only SHA-256 hashes are stored; plaintext is shown once at mint time.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import secrets
import threading
import time
from pathlib import Path
from typing import Any

from sentence_reading.cache.paper_cache import project_root
from sentence_reading.llm.auth_accounts import accounts_path
from sentence_reading.llm.auth_google import sanitize_uid
from sentence_reading.llm.env import load_asr_env

log = logging.getLogger(__name__)

_LOCK = threading.RLock()

STATUS_NONE = "none"
STATUS_PENDING = "pending"
STATUS_ALLOWED = "allowed"
STATUS_DENIED = "denied"
STATUS_BYOK = "byok"  # reserved — own API keys (follow-up)

PAID_STATUSES = frozenset({STATUS_ALLOWED, STATUS_BYOK})

# Ambiguous chars removed (0/O, 1/I/L) — OTP-style readability.
_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def events_path() -> Path:
    return project_root() / "data" / "auth" / "access_events.json"


def invites_path() -> Path:
    return project_root() / "data" / "auth" / "invite_codes.json"


def access_gate_enabled() -> bool:
    """
    ASR_ACCESS_GATE=0 → off.
    ASR_ACCESS_GATE=1 → on.
    unset → on (cost protection default for Cloud Run).
    """
    load_asr_env()
    v = (os.environ.get("ASR_ACCESS_GATE") or "").strip().lower()
    if v in ("0", "false", "no", "off"):
        return False
    if v in ("1", "true", "yes", "on"):
        return True
    return True


def normalize_invite_code(raw: str | None) -> str:
    """Uppercase, strip separators/spaces — EDGE: None → empty."""
    if raw is None:
        return ""
    s = str(raw).strip().upper()
    # Allow users to type TqG3-V12T or TqG3V12T or TqG3 V12T
    out = []
    for ch in s:
        if ch.isalnum():
            out.append(ch)
    return "".join(out)


def hash_invite_code(raw: str | None) -> str:
    norm = normalize_invite_code(raw)
    if not norm:
        return ""
    return hashlib.sha256(norm.encode("utf-8")).hexdigest()


def format_invite_code(compact: str) -> str:
    """XXXX-XXXX display form from 8 alnum chars."""
    c = normalize_invite_code(compact)
    if len(c) != 8:
        return c
    return f"{c[:4]}-{c[4:]}"


def generate_invite_code() -> str:
    """Cryptographically random OTP-style code: ABCD-EFGH."""
    chars = [secrets.choice(_CODE_ALPHABET) for _ in range(8)]
    return format_invite_code("".join(chars))


def _read_json(path: Path, default: dict[str, Any]) -> dict[str, Any]:
    if not path.is_file():
        return dict(default)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return dict(default)
    if not isinstance(data, dict):
        return dict(default)
    return data


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def _read_accounts() -> dict[str, Any]:
    path = accounts_path()
    if not path.is_file():
        return {"version": 1, "users": {}, "by_provider": {}}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"version": 1, "users": {}, "by_provider": {}}
    if not isinstance(data, dict):
        return {"version": 1, "users": {}, "by_provider": {}}
    users = data.get("users") if isinstance(data.get("users"), dict) else {}
    by_p = data.get("by_provider") if isinstance(data.get("by_provider"), dict) else {}
    return {"version": 1, "users": users, "by_provider": by_p}


def _write_accounts(store: dict[str, Any]) -> None:
    path = accounts_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = json.dumps(store, ensure_ascii=False, indent=2) + "\n"
    path.write_text(raw, encoding="utf-8")
    try:
        from sentence_reading.llm.gcs_sync import object_name, upload_bytes

        obj = object_name("auth", "accounts.json")
        if obj:
            upload_bytes(
                obj, raw.encode("utf-8"), content_type="application/json; charset=utf-8"
            )
    except Exception as exc:  # noqa: BLE001
        log.debug("accounts gcs push skip: %s", exc)


def _read_invites() -> dict[str, Any]:
    data = _read_json(invites_path(), {"version": 1, "codes": []})
    codes = data.get("codes")
    if not isinstance(codes, list):
        codes = []
    data["codes"] = codes
    return data


def _write_invites(store: dict[str, Any]) -> None:
    _write_json(invites_path(), store)


def invite_pool_nonempty() -> bool:
    with _LOCK:
        store = _read_invites()
        for row in store["codes"]:
            if isinstance(row, dict) and row.get("status") == "open":
                return True
        return False


def mint_invite_code(
    *,
    admin_uid: str = "",
    admin_email: str = "",
    note: str = "",
) -> dict[str, Any]:
    """
    Create one single-use invite. Returns plaintext `code` once.
    Store only hash + metadata.
    """
    # Retry on improbable hash collision
    plain = ""
    digest = ""
    for _ in range(8):
        plain = generate_invite_code()
        digest = hash_invite_code(plain)
        if digest:
            break
    if not digest or not plain:
        raise ValueError("mint_failed")

    now = int(time.time())
    with _LOCK:
        store = _read_invites()
        # EDGE: ensure hash uniqueness
        for row in store["codes"]:
            if isinstance(row, dict) and row.get("hash") == digest:
                raise ValueError("mint_collision")
        store["codes"].append(
            {
                "hash": digest,
                "status": "open",  # open | redeemed | revoked
                "created_at": now,
                "created_by": sanitize_uid(admin_uid) or (admin_email or "")[:120],
                "note": (note or "")[:200],
                "redeemed_by": "",
                "redeemed_at": None,
            }
        )
        # EDGE: cap archive
        if len(store["codes"]) > 2000:
            store["codes"] = store["codes"][-2000:]
        _write_invites(store)

    append_event(
        {
            "type": "invite_minted",
            "admin": admin_email,
            "message": "new OTP invite minted",
            "hint": plain[:2] + "****",
        }
    )
    return {
        "code": plain,
        "created_at": now,
        "single_use": True,
    }


def list_open_invite_meta(*, limit: int = 20) -> list[dict[str, Any]]:
    """Admin view — never returns plaintext codes."""
    with _LOCK:
        store = _read_invites()
        out: list[dict[str, Any]] = []
        for row in reversed(store["codes"]):
            if not isinstance(row, dict):
                continue
            if row.get("status") != "open":
                continue
            out.append(
                {
                    "hash_prefix": str(row.get("hash") or "")[:8],
                    "created_at": row.get("created_at"),
                    "created_by": row.get("created_by") or "",
                    "note": row.get("note") or "",
                }
            )
            if len(out) >= max(1, min(limit, 100)):
                break
        return out


def _access_blob(row: dict[str, Any] | None) -> dict[str, Any]:
    if not isinstance(row, dict):
        return {"status": STATUS_NONE}
    acc = row.get("access")
    if not isinstance(acc, dict):
        return {"status": STATUS_NONE}
    st = str(acc.get("status") or STATUS_NONE).strip().lower()
    if st not in {
        STATUS_NONE,
        STATUS_PENDING,
        STATUS_ALLOWED,
        STATUS_DENIED,
        STATUS_BYOK,
    }:
        st = STATUS_NONE
    out = dict(acc)
    out["status"] = st
    return out


def get_access_for_uid(uid: str | None) -> dict[str, Any]:
    uid_s = sanitize_uid(uid or "")
    if not uid_s:
        return {"status": STATUS_NONE}
    with _LOCK:
        store = _read_accounts()
        row = store["users"].get(uid_s)
        return _access_blob(row if isinstance(row, dict) else None)


def public_access_view(
    uid: str | None,
    *,
    email: str = "",
    is_admin: bool = False,
) -> dict[str, Any]:
    enabled = access_gate_enabled()
    acc = get_access_for_uid(uid)
    status = str(acc.get("status") or STATUS_NONE)
    if not enabled:
        can = True
        effective = "open"
    elif is_admin:
        can = True
        effective = "admin"
        if status == STATUS_NONE:
            status = STATUS_ALLOWED
    else:
        can = status in PAID_STATUSES
        effective = status
    return {
        "gate_enabled": enabled,
        "invite_pool_ready": invite_pool_nonempty(),
        "status": status,
        "effective": effective,
        "can_use_paid": can,
        "invited_at": acc.get("invited_at"),
        "decided_at": acc.get("decided_at"),
        "decision_note": acc.get("note") or "",
        "code_format": "XXXX-XXXX",
    }


def append_event(event: dict[str, Any]) -> None:
    path = events_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with _LOCK:
        items: list[Any] = []
        if path.is_file():
            try:
                raw = json.loads(path.read_text(encoding="utf-8"))
                if isinstance(raw, dict) and isinstance(raw.get("events"), list):
                    items = list(raw["events"])
                elif isinstance(raw, list):
                    items = list(raw)
            except (OSError, json.JSONDecodeError):
                items = []
        event = dict(event)
        event.setdefault("ts", int(time.time()))
        items.append(event)
        if len(items) > 500:
            items = items[-500:]
        path.write_text(
            json.dumps({"version": 1, "events": items}, ensure_ascii=False, indent=2)
            + "\n",
            encoding="utf-8",
        )


def list_events(*, limit: int = 50) -> list[dict[str, Any]]:
    path = events_path()
    if not path.is_file():
        return []
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if isinstance(raw, dict) and isinstance(raw.get("events"), list):
        items = raw["events"]
    elif isinstance(raw, list):
        items = raw
    else:
        return []
    out = [it for it in items if isinstance(it, dict)]
    return out[-max(1, min(limit, 200)) :]


def list_pending() -> list[dict[str, Any]]:
    with _LOCK:
        store = _read_accounts()
        out: list[dict[str, Any]] = []
        for uid, row in store["users"].items():
            if not isinstance(row, dict):
                continue
            acc = _access_blob(row)
            if acc.get("status") != STATUS_PENDING:
                continue
            out.append(
                {
                    "uid": uid,
                    "email": str(row.get("email") or ""),
                    "name": str(row.get("name") or ""),
                    "invited_at": acc.get("invited_at"),
                }
            )
        out.sort(key=lambda x: int(x.get("invited_at") or 0))
        return out


def redeem_invite(uid: str, code: str, *, email: str = "", name: str = "") -> dict[str, Any]:
    """
    Match OTP invite hash → mark code redeemed → user pending.
    Raises ValueError with stable codes.
    """
    uid_s = sanitize_uid(uid)
    if not uid_s:
        raise ValueError("auth_required")
    if not access_gate_enabled():
        raise ValueError("gate_disabled")
    compact = normalize_invite_code(code)
    if not compact:
        raise ValueError("empty_code")
    # EDGE: wrong length after normalize
    if len(compact) != 8:
        append_event(
            {
                "type": "invite_failed",
                "uid": uid_s,
                "email": email,
                "message": "malformed invite code",
            }
        )
        raise ValueError("bad_code")

    digest = hash_invite_code(compact)
    now = int(time.time())

    with _LOCK:
        inv = _read_invites()
        matched: dict[str, Any] | None = None
        for row in inv["codes"]:
            if not isinstance(row, dict):
                continue
            h = str(row.get("hash") or "")
            if not h or not hmac.compare_digest(h, digest):
                continue
            matched = row
            break

        if matched is None:
            append_event(
                {
                    "type": "invite_failed",
                    "uid": uid_s,
                    "email": email,
                    "message": "unknown invite code",
                }
            )
            raise ValueError("bad_code")

        st_code = str(matched.get("status") or "")
        if st_code == "revoked":
            raise ValueError("code_revoked")
        if st_code == "redeemed":
            raise ValueError("code_used")
        if st_code != "open":
            raise ValueError("bad_code")

        # consume invite (single-use)
        matched["status"] = "redeemed"
        matched["redeemed_by"] = uid_s
        matched["redeemed_at"] = now
        _write_invites(inv)

        store = _read_accounts()
        row = store["users"].get(uid_s)
        if not isinstance(row, dict):
            row = {
                "uid": uid_s,
                "email": email or "",
                "name": name or "",
                "picture": "",
                "providers": {},
            }
            store["users"][uid_s] = row
        acc = _access_blob(row)
        if acc.get("status") in (STATUS_ALLOWED, STATUS_BYOK):
            return public_access_view(uid_s, email=email)
        acc["status"] = STATUS_PENDING
        acc["invited_at"] = now
        acc["invite_hash_prefix"] = digest[:8]
        acc.pop("decided_at", None)
        acc.pop("decided_by", None)
        acc["note"] = ""
        row["access"] = acc
        store["users"][uid_s] = row
        _write_accounts(store)

    append_event(
        {
            "type": "invite_pending",
            "uid": uid_s,
            "email": email,
            "name": name,
            "message": "OTP redeemed — awaiting admin allow/deny",
        }
    )
    return public_access_view(uid_s, email=email)


def decide_access(
    target_uid: str,
    decision: str,
    *,
    admin_uid: str = "",
    admin_email: str = "",
    note: str = "",
) -> dict[str, Any]:
    uid_s = sanitize_uid(target_uid)
    if not uid_s:
        raise ValueError("bad_uid")
    d = (decision or "").strip().lower()
    if d in ("allow", "allowed", "approve", "approved"):
        new_st = STATUS_ALLOWED
    elif d in ("deny", "denied", "reject", "rejected"):
        new_st = STATUS_DENIED
    else:
        raise ValueError("bad_decision")

    now = int(time.time())
    with _LOCK:
        store = _read_accounts()
        row = store["users"].get(uid_s)
        if not isinstance(row, dict):
            raise ValueError("user_not_found")
        acc = _access_blob(row)
        acc["status"] = new_st
        acc["decided_at"] = now
        acc["decided_by"] = sanitize_uid(admin_uid) or (admin_email or "")[:120]
        acc["note"] = (note or "")[:300]
        row["access"] = acc
        store["users"][uid_s] = row
        _write_accounts(store)
        email = str(row.get("email") or "")

    append_event(
        {
            "type": f"access_{new_st}",
            "uid": uid_s,
            "email": email,
            "admin": admin_email,
            "message": note or new_st,
        }
    )
    return public_access_view(uid_s, email=email)


def user_may_use_paid(
    uid: str | None,
    *,
    email: str = "",
    is_admin: bool = False,
) -> bool:
    if not access_gate_enabled():
        return True
    if is_admin:
        return True
    st = str(get_access_for_uid(uid).get("status") or STATUS_NONE)
    return st in PAID_STATUSES
