# -*- coding: utf-8 -*-
"""Access gate: random OTP-style invite codes + admin allow/deny (design/67).

Codes look like TqG3-V12T — generated by the server (admin never invents them).
Only SHA-256 hashes are stored; plaintext is shown once at mint time.

Hardening (0.2.76):
- Invites expire after ASR_INVITE_TTL_HOURS (default 48; 0 = no expiry).
- Redeem attempts are rate-limited per uid (ASR_INVITE_REDEEM_MAX /
  ASR_INVITE_REDEEM_WINDOW_SEC) to blunt online guessing.

GCS durability (0.2.86 · design/69):
- invite_codes / access_events / redeem_attempts push+pull like accounts.json.
- WHY: Cloud Run ephemeral disk + multi-instance must share one gate truth.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import os
import secrets
import threading
import time
from pathlib import Path
from typing import Any

from sentence_reading.cache.paper_cache import project_root
from sentence_reading.llm.auth_accounts import accounts_path
from sentence_reading.llm.auth_google import sanitize_uid
from sentence_reading.llm.env import load_asr_env

log = logging.getLogger(__name__)

_LOCK = threading.RLock()

STATUS_NONE = "none"
STATUS_PENDING = "pending"
STATUS_ALLOWED = "allowed"
STATUS_DENIED = "denied"
STATUS_BYOK = "byok"  # reserved — own API keys (follow-up)

PAID_STATUSES = frozenset({STATUS_ALLOWED, STATUS_BYOK})

# Ambiguous chars removed (0/O, 1/I/L) — OTP-style readability.
_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def events_path() -> Path:
    return project_root() / "data" / "auth" / "access_events.json"


def invites_path() -> Path:
    return project_root() / "data" / "auth" / "invite_codes.json"


def redeem_attempts_path() -> Path:
    """Persisted redeem attempt windows (per uid) — survives process restart."""
    return project_root() / "data" / "auth" / "redeem_attempts.json"


# WHY: redeemed must win over open so a late pull cannot resurrect a used OTP.
_INVITE_STATUS_RANK = {
    "open": 1,
    "expired": 2,
    "revoked": 3,
    "redeemed": 4,
}


def _auth_gcs_object(filename: str) -> str | None:
    """Shared auth object under {prefix}/auth/… — never under users/{uid}/."""
    try:
        from sentence_reading.llm.gcs_sync import object_name

        return object_name("auth", filename)
    except Exception:  # noqa: BLE001
        return None


def _push_auth_json(path: Path, filename: str) -> None:
    """
    Local JSON → GCS. Fail-soft: local remains source for this process.
    INVARIANT: plaintext invite codes are never written to these files.
    """
    try:
        from sentence_reading.llm.gcs_sync import upload_bytes

        obj = _auth_gcs_object(filename)
        if not obj or not path.is_file():
            return
        raw = path.read_bytes()
        if not raw:
            return
        upload_bytes(
            obj, raw, content_type="application/json; charset=utf-8"
        )
    except Exception as exc:  # noqa: BLE001
        log.debug("access_gate gcs push skip %s: %s", filename, exc)


def _download_auth_json(filename: str) -> dict[str, Any] | None:
    """GCS → dict. Miss/disabled/error → None (caller keeps local)."""
    try:
        from sentence_reading.llm.gcs_sync import download_bytes

        obj = _auth_gcs_object(filename)
        if not obj:
            return None
        raw = download_bytes(obj)
        if not raw:
            return None
        data = json.loads(raw.decode("utf-8"))
        if not isinstance(data, dict):
            return None
        return data
    except Exception as exc:  # noqa: BLE001
        log.debug("access_gate gcs pull skip %s: %s", filename, exc)
        return None


def _merge_invite_stores(
    local: dict[str, Any], remote: dict[str, Any]
) -> dict[str, Any]:
    """Same hash → higher status rank wins; tie → newer redeemed/created."""
    by_hash: dict[str, dict[str, Any]] = {}
    for src in (local, remote):
        codes = src.get("codes") if isinstance(src.get("codes"), list) else []
        for row in codes:
            if not isinstance(row, dict):
                continue
            h = str(row.get("hash") or "").strip()
            if not h or len(h) < 16:
                continue
            prev = by_hash.get(h)
            if prev is None:
                by_hash[h] = dict(row)
                continue
            r_new = _INVITE_STATUS_RANK.get(str(row.get("status") or ""), 0)
            r_old = _INVITE_STATUS_RANK.get(str(prev.get("status") or ""), 0)
            if r_new > r_old:
                by_hash[h] = dict(row)
                continue
            if r_new < r_old:
                continue
            try:
                t_new = int(row.get("redeemed_at") or row.get("created_at") or 0)
                t_old = int(prev.get("redeemed_at") or prev.get("created_at") or 0)
            except (TypeError, ValueError):
                t_new, t_old = 0, 0
            if t_new >= t_old:
                by_hash[h] = dict(row)
    return {"version": 1, "codes": list(by_hash.values())}


def _merge_event_stores(
    local: dict[str, Any], remote: dict[str, Any]
) -> dict[str, Any]:
    """Dedupe admin notification events; keep newest 500."""
    seen: set[tuple[Any, ...]] = set()
    items: list[dict[str, Any]] = []
    for src in (local, remote):
        raw_ev = src.get("events")
        if not isinstance(raw_ev, list):
            continue
        for it in raw_ev:
            if not isinstance(it, dict):
                continue
            key = (
                it.get("ts"),
                it.get("type"),
                it.get("uid"),
                it.get("message"),
            )
            if key in seen:
                continue
            seen.add(key)
            items.append(dict(it))
    items.sort(key=lambda x: int(x.get("ts") or 0))
    if len(items) > 500:
        items = items[-500:]
    return {"version": 1, "events": items}


def _merge_redeem_stores(
    local: dict[str, Any], remote: dict[str, Any]
) -> dict[str, Any]:
    """Union per-uid attempt stamps (rate-limit must not reset on other instance)."""
    by: dict[str, list[int]] = {}
    for src in (local, remote):
        raw = src.get("by_uid")
        if not isinstance(raw, dict):
            continue
        for uid, stamps in raw.items():
            uid_s = sanitize_uid(str(uid))
            if not uid_s or not isinstance(stamps, list):
                continue
            bucket = by.setdefault(uid_s, [])
            for x in stamps:
                try:
                    bucket.append(int(x))
                except (TypeError, ValueError):
                    continue
    out_by: dict[str, list[int]] = {}
    for uid_s, stamps in by.items():
        uniq = sorted(set(stamps))
        out_by[uid_s] = uniq[-40:]
    if len(out_by) > 5000:
        # EDGE: cap map size — keep newest uids by last stamp
        ranked = sorted(
            out_by.items(),
            key=lambda kv: kv[1][-1] if kv[1] else 0,
        )
        out_by = dict(ranked[-4000:])
    return {"version": 1, "by_uid": out_by}


def refresh_access_gate_from_gcs() -> bool:
    """
    Pull shared gate truth before mint/redeem/decide/paid checks.

    WHY before critical ops: another Cloud Run instance may have minted/allowed.
    Fail-soft: GCS down → keep local (may deny paid — fail-closed for cost).
    """
    changed = False
    try:
        from sentence_reading.llm.auth_accounts import pull_accounts_from_gcs

        if pull_accounts_from_gcs():
            changed = True
    except Exception as exc:  # noqa: BLE001
        log.debug("access_gate accounts pull skip: %s", exc)

    remote_inv = _download_auth_json("invite_codes.json")
    remote_ev = _download_auth_json("access_events.json")
    remote_ra = _download_auth_json("redeem_attempts.json")

    with _LOCK:
        if remote_inv is not None:
            merged = _merge_invite_stores(_read_invites(), remote_inv)
            _write_json(invites_path(), merged)
            changed = True
        if remote_ev is not None:
            local_ev = _read_json(events_path(), {"version": 1, "events": []})
            merged_ev = _merge_event_stores(local_ev, remote_ev)
            _write_json(events_path(), merged_ev)
            changed = True
        if remote_ra is not None:
            merged_ra = _merge_redeem_stores(_read_redeem_attempts(), remote_ra)
            _write_json(redeem_attempts_path(), merged_ra)
            changed = True
    return changed


def access_gate_enabled() -> bool:
    """
    ASR_ACCESS_GATE=0 → off.
    ASR_ACCESS_GATE=1 → on.
    unset → on (cost protection default for Cloud Run).
    """
    load_asr_env()
    v = (os.environ.get("ASR_ACCESS_GATE") or "").strip().lower()
    if v in ("0", "false", "no", "off"):
        return False
    if v in ("1", "true", "yes", "on"):
        return True
    return True



def invite_ttl_seconds() -> int:
    """
    Invite lifetime from mint.

    ASR_INVITE_TTL_HOURS:
      unset → 48h
      0 / false / off → no expiry (legacy/open labs)
      negative / garbage → 48h (safe default)
    """
    load_asr_env()
    raw = (os.environ.get("ASR_INVITE_TTL_HOURS") or "").strip().lower()
    if raw in ("0", "false", "no", "off"):
        return 0
    if not raw:
        return 48 * 3600
    try:
        hours = float(raw)
    except ValueError:
        return 48 * 3600
    if hours < 0:
        return 48 * 3600
    if hours == 0:
        return 0
    # EDGE: absurd values (e.g. 1e12 hours) clamp to 365d
    secs = int(hours * 3600)
    return min(secs, 365 * 24 * 3600)


def redeem_max_attempts() -> int:
    """Max redeem tries per uid inside the window. EDGE: <=0 → 10."""
    load_asr_env()
    raw = (os.environ.get("ASR_INVITE_REDEEM_MAX") or "").strip()
    if not raw:
        return 10
    try:
        n = int(raw)
    except ValueError:
        return 10
    if n <= 0:
        return 10
    return min(n, 1000)


def redeem_window_seconds() -> int:
    """Sliding window for redeem attempts. EDGE: <=0 → 900s."""
    load_asr_env()
    raw = (os.environ.get("ASR_INVITE_REDEEM_WINDOW_SEC") or "").strip()
    if not raw:
        return 900
    try:
        n = int(raw)
    except ValueError:
        return 900
    if n <= 0:
        return 900
    return min(n, 7 * 24 * 3600)


def _read_redeem_attempts() -> dict[str, Any]:
    return _read_json(redeem_attempts_path(), {"version": 1, "by_uid": {}})


def _write_redeem_attempts(store: dict[str, Any]) -> None:
    _write_json(redeem_attempts_path(), store)
    # WHY: rate-limit counters must follow the user across instances (design/69)
    _push_auth_json(redeem_attempts_path(), "redeem_attempts.json")


def check_redeem_rate_limit(uid: str, *, now: int | None = None) -> None:
    """
    Raise ValueError('rate_limited') when uid exceeded max attempts in window.

    WHY before hash lookup: stop online guessing even with wrong codes.
    Empty-code callers should skip this (handled in redeem_invite).
    """
    uid_s = sanitize_uid(uid)
    if not uid_s:
        raise ValueError("auth_required")
    ts = int(now if now is not None else time.time())
    window = redeem_window_seconds()
    max_n = redeem_max_attempts()
    cutoff = ts - window
    with _LOCK:
        store = _read_redeem_attempts()
        by = store.get("by_uid")
        if not isinstance(by, dict):
            by = {}
            store["by_uid"] = by
        raw_list = by.get(uid_s)
        stamps: list[int] = []
        if isinstance(raw_list, list):
            for x in raw_list:
                try:
                    ix = int(x)
                except (TypeError, ValueError):
                    continue
                if ix >= cutoff:
                    stamps.append(ix)
        if len(stamps) >= max_n:
            append_event(
                {
                    "type": "invite_rate_limited",
                    "uid": uid_s,
                    "message": "redeem rate limit hit",
                    "attempts": len(stamps),
                    "window_sec": window,
                }
            )
            raise ValueError("rate_limited")
        stamps.append(ts)
        by[uid_s] = stamps[-(max_n * 2) :]
        # EDGE: prune idle uids
        if len(by) > 5000:
            keep = {}
            for k, v in list(by.items())[-4000:]:
                keep[k] = v
            store["by_uid"] = keep
        _write_redeem_attempts(store)


def invite_is_expired(row: dict[str, Any], *, now: int | None = None) -> bool:
    """True when open invite past expires_at (or created_at+ttl fallback)."""
    ts = int(now if now is not None else time.time())
    exp = row.get("expires_at")
    if exp is None:
        # Legacy rows minted before 0.2.76 — apply current TTL from created_at
        ttl = invite_ttl_seconds()
        if ttl <= 0:
            return False
        try:
            created = int(row.get("created_at") or 0)
        except (TypeError, ValueError):
            created = 0
        if created <= 0:
            return False
        exp = created + ttl
    try:
        exp_i = int(exp)
    except (TypeError, ValueError):
        return False
    if exp_i <= 0:
        return False
    return ts > exp_i


def normalize_invite_code(raw: str | None) -> str:
    """Uppercase, strip separators/spaces — EDGE: None → empty."""
    if raw is None:
        return ""
    s = str(raw).strip().upper()
    # Allow users to type TqG3-V12T or TqG3V12T or TqG3 V12T
    out = []
    for ch in s:
        if ch.isalnum():
            out.append(ch)
    return "".join(out)


def hash_invite_code(raw: str | None) -> str:
    norm = normalize_invite_code(raw)
    if not norm:
        return ""
    return hashlib.sha256(norm.encode("utf-8")).hexdigest()


def format_invite_code(compact: str) -> str:
    """XXXX-XXXX display form from 8 alnum chars."""
    c = normalize_invite_code(compact)
    if len(c) != 8:
        return c
    return f"{c[:4]}-{c[4:]}"


def generate_invite_code() -> str:
    """Cryptographically random OTP-style code: ABCD-EFGH."""
    chars = [secrets.choice(_CODE_ALPHABET) for _ in range(8)]
    return format_invite_code("".join(chars))


def _read_json(path: Path, default: dict[str, Any]) -> dict[str, Any]:
    if not path.is_file():
        return dict(default)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return dict(default)
    if not isinstance(data, dict):
        return dict(default)
    return data


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def _read_accounts() -> dict[str, Any]:
    path = accounts_path()
    if not path.is_file():
        return {"version": 1, "users": {}, "by_provider": {}}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"version": 1, "users": {}, "by_provider": {}}
    if not isinstance(data, dict):
        return {"version": 1, "users": {}, "by_provider": {}}
    users = data.get("users") if isinstance(data.get("users"), dict) else {}
    by_p = data.get("by_provider") if isinstance(data.get("by_provider"), dict) else {}
    return {"version": 1, "users": users, "by_provider": by_p}


def _write_accounts(store: dict[str, Any]) -> None:
    path = accounts_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = json.dumps(store, ensure_ascii=False, indent=2) + "\n"
    path.write_text(raw, encoding="utf-8")
    try:
        from sentence_reading.llm.gcs_sync import object_name, upload_bytes

        obj = object_name("auth", "accounts.json")
        if obj:
            upload_bytes(
                obj, raw.encode("utf-8"), content_type="application/json; charset=utf-8"
            )
    except Exception as exc:  # noqa: BLE001
        log.debug("accounts gcs push skip: %s", exc)


def _read_invites() -> dict[str, Any]:
    data = _read_json(invites_path(), {"version": 1, "codes": []})
    codes = data.get("codes")
    if not isinstance(codes, list):
        codes = []
    data["codes"] = codes
    return data


def _write_invites(store: dict[str, Any]) -> None:
    _write_json(invites_path(), store)
    # WHY: mint on instance A must be redeemable on B (design/69)
    _push_auth_json(invites_path(), "invite_codes.json")


def invite_pool_nonempty() -> bool:
    with _LOCK:
        store = _read_invites()
        for row in store["codes"]:
            if isinstance(row, dict) and row.get("status") == "open":
                return True
        return False


def mint_invite_code(
    *,
    admin_uid: str = "",
    admin_email: str = "",
    note: str = "",
) -> dict[str, Any]:
    """
    Create one single-use invite. Returns plaintext `code` once.
    Store only hash + metadata (+ expires_at when TTL > 0).
    """
    # WHY: pick up remote pool before appending (avoid blind local-only mint)
    refresh_access_gate_from_gcs()
    # Retry on improbable hash collision
    plain = ""
    digest = ""
    for _ in range(8):
        plain = generate_invite_code()
        digest = hash_invite_code(plain)
        if digest:
            break
    if not digest or not plain:
        raise ValueError("mint_failed")

    now = int(time.time())
    with _LOCK:
        store = _read_invites()
        # EDGE: ensure hash uniqueness
        for row in store["codes"]:
            if isinstance(row, dict) and row.get("hash") == digest:
                raise ValueError("mint_collision")
        ttl = invite_ttl_seconds()
        expires_at = (now + ttl) if ttl > 0 else None
        store["codes"].append(
            {
                "hash": digest,
                "status": "open",  # open | redeemed | revoked | expired
                "created_at": now,
                "expires_at": expires_at,
                "created_by": sanitize_uid(admin_uid) or (admin_email or "")[:120],
                "note": (note or "")[:200],
                "redeemed_by": "",
                "redeemed_at": None,
            }
        )
        # EDGE: cap archive
        if len(store["codes"]) > 2000:
            store["codes"] = store["codes"][-2000:]
        _write_invites(store)

    append_event(
        {
            "type": "invite_minted",
            "admin": admin_email,
            "message": "new OTP invite minted",
            "hint": plain[:2] + "****",
        }
    )
    ttl = invite_ttl_seconds()
    return {
        "code": plain,
        "created_at": now,
        "expires_at": (now + ttl) if ttl > 0 else None,
        "ttl_seconds": ttl,
        "single_use": True,
    }


def list_open_invite_meta(*, limit: int = 20) -> list[dict[str, Any]]:
    """Admin view — never returns plaintext codes."""
    refresh_access_gate_from_gcs()
    with _LOCK:
        store = _read_invites()
        out: list[dict[str, Any]] = []
        dirty = False
        for row in reversed(store["codes"]):
            if not isinstance(row, dict):
                continue
            if row.get("status") != "open":
                continue
            if invite_is_expired(row):
                row["status"] = "expired"
                dirty = True
                continue
            out.append(
                {
                    "hash_prefix": str(row.get("hash") or "")[:8],
                    "created_at": row.get("created_at"),
                    "expires_at": row.get("expires_at"),
                    "created_by": row.get("created_by") or "",
                    "note": row.get("note") or "",
                }
            )
            if len(out) >= max(1, min(limit, 100)):
                break
        if dirty:
            _write_invites(store)
        return out


def _access_blob(row: dict[str, Any] | None) -> dict[str, Any]:
    if not isinstance(row, dict):
        return {"status": STATUS_NONE}
    acc = row.get("access")
    if not isinstance(acc, dict):
        return {"status": STATUS_NONE}
    st = str(acc.get("status") or STATUS_NONE).strip().lower()
    if st not in {
        STATUS_NONE,
        STATUS_PENDING,
        STATUS_ALLOWED,
        STATUS_DENIED,
        STATUS_BYOK,
    }:
        st = STATUS_NONE
    out = dict(acc)
    out["status"] = st
    return out


def get_access_for_uid(uid: str | None) -> dict[str, Any]:
    uid_s = sanitize_uid(uid or "")
    if not uid_s:
        return {"status": STATUS_NONE}
    with _LOCK:
        store = _read_accounts()
        row = store["users"].get(uid_s)
        return _access_blob(row if isinstance(row, dict) else None)


def public_access_view(
    uid: str | None,
    *,
    email: str = "",
    is_admin: bool = False,
) -> dict[str, Any]:
    enabled = access_gate_enabled()
    acc = get_access_for_uid(uid)
    status = str(acc.get("status") or STATUS_NONE)
    if not enabled:
        can = True
        effective = "open"
    elif is_admin:
        can = True
        effective = "admin"
        if status == STATUS_NONE:
            status = STATUS_ALLOWED
    else:
        can = status in PAID_STATUSES
        effective = status
    return {
        "gate_enabled": enabled,
        "invite_pool_ready": invite_pool_nonempty(),
        "status": status,
        "effective": effective,
        "can_use_paid": can,
        # WHY expose is_admin: client must fail-closed hide mint/decide UI.
        # Server still enforces mint/decide; UI flag is not authorization.
        "is_admin": bool(is_admin),
        "invited_at": acc.get("invited_at"),
        "decided_at": acc.get("decided_at"),
        "decision_note": acc.get("note") or "",
        "code_format": "XXXX-XXXX",
    }


def append_event(event: dict[str, Any]) -> None:
    path = events_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with _LOCK:
        items: list[Any] = []
        if path.is_file():
            try:
                raw = json.loads(path.read_text(encoding="utf-8"))
                if isinstance(raw, dict) and isinstance(raw.get("events"), list):
                    items = list(raw["events"])
                elif isinstance(raw, list):
                    items = list(raw)
            except (OSError, json.JSONDecodeError):
                items = []
        event = dict(event)
        event.setdefault("ts", int(time.time()))
        items.append(event)
        if len(items) > 500:
            items = items[-500:]
        path.write_text(
            json.dumps({"version": 1, "events": items}, ensure_ascii=False, indent=2)
            + "\n",
            encoding="utf-8",
        )
    # WHY: admin notifications must be visible on any instance (design/69)
    _push_auth_json(path, "access_events.json")


def list_events(*, limit: int = 50) -> list[dict[str, Any]]:
    refresh_access_gate_from_gcs()
    path = events_path()
    if not path.is_file():
        return []
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if isinstance(raw, dict) and isinstance(raw.get("events"), list):
        items = raw["events"]
    elif isinstance(raw, list):
        items = raw
    else:
        return []
    out = [it for it in items if isinstance(it, dict)]
    return out[-max(1, min(limit, 200)) :]


def list_pending() -> list[dict[str, Any]]:
    # WHY: pending queue is on accounts.json — refresh before admin UI
    refresh_access_gate_from_gcs()
    with _LOCK:
        store = _read_accounts()
        out: list[dict[str, Any]] = []
        for uid, row in store["users"].items():
            if not isinstance(row, dict):
                continue
            acc = _access_blob(row)
            if acc.get("status") != STATUS_PENDING:
                continue
            out.append(
                {
                    "uid": uid,
                    "email": str(row.get("email") or ""),
                    "name": str(row.get("name") or ""),
                    "invited_at": acc.get("invited_at"),
                }
            )
        out.sort(key=lambda x: int(x.get("invited_at") or 0))
        return out


def redeem_invite(uid: str, code: str, *, email: str = "", name: str = "") -> dict[str, Any]:
    """
    Match OTP invite hash → mark code redeemed → user pending.
    Raises ValueError with stable codes.
    """
    uid_s = sanitize_uid(uid)
    if not uid_s:
        raise ValueError("auth_required")
    if not access_gate_enabled():
        raise ValueError("gate_disabled")
    # WHY: code may have been minted on another instance (design/69)
    refresh_access_gate_from_gcs()
    compact = normalize_invite_code(code)
    if not compact:
        raise ValueError("empty_code")
    # Non-empty guesses count toward rate limit (empty skipped above).
    now = int(time.time())
    check_redeem_rate_limit(uid_s, now=now)
    # EDGE: wrong length after normalize
    if len(compact) != 8:
        append_event(
            {
                "type": "invite_failed",
                "uid": uid_s,
                "email": email,
                "message": "malformed invite code",
            }
        )
        raise ValueError("bad_code")

    digest = hash_invite_code(compact)

    with _LOCK:
        inv = _read_invites()
        matched: dict[str, Any] | None = None
        for row in inv["codes"]:
            if not isinstance(row, dict):
                continue
            h = str(row.get("hash") or "")
            if not h or not hmac.compare_digest(h, digest):
                continue
            matched = row
            break

        if matched is None:
            append_event(
                {
                    "type": "invite_failed",
                    "uid": uid_s,
                    "email": email,
                    "message": "unknown invite code",
                }
            )
            raise ValueError("bad_code")

        st_code = str(matched.get("status") or "")
        if st_code == "revoked":
            raise ValueError("code_revoked")
        if st_code == "redeemed":
            raise ValueError("code_used")
        if st_code == "expired":
            raise ValueError("code_expired")
        if st_code != "open":
            raise ValueError("bad_code")

        # EDGE: TTL elapsed → mark expired (not redeemed)
        if invite_is_expired(matched, now=now):
            matched["status"] = "expired"
            _write_invites(inv)
            append_event(
                {
                    "type": "invite_expired",
                    "uid": uid_s,
                    "email": email,
                    "message": "invite past expires_at",
                }
            )
            raise ValueError("code_expired")

        # consume invite (single-use)
        matched["status"] = "redeemed"
        matched["redeemed_by"] = uid_s
        matched["redeemed_at"] = now
        _write_invites(inv)

        store = _read_accounts()
        row = store["users"].get(uid_s)
        if not isinstance(row, dict):
            row = {
                "uid": uid_s,
                "email": email or "",
                "name": name or "",
                "picture": "",
                "providers": {},
            }
            store["users"][uid_s] = row
        acc = _access_blob(row)
        if acc.get("status") in (STATUS_ALLOWED, STATUS_BYOK):
            return public_access_view(uid_s, email=email)
        acc["status"] = STATUS_PENDING
        acc["invited_at"] = now
        acc["invite_hash_prefix"] = digest[:8]
        acc.pop("decided_at", None)
        acc.pop("decided_by", None)
        acc["note"] = ""
        row["access"] = acc
        store["users"][uid_s] = row
        _write_accounts(store)

    append_event(
        {
            "type": "invite_pending",
            "uid": uid_s,
            "email": email,
            "name": name,
            "message": "OTP redeemed — awaiting admin allow/deny",
        }
    )
    return public_access_view(uid_s, email=email)


def decide_access(
    target_uid: str,
    decision: str,
    *,
    admin_uid: str = "",
    admin_email: str = "",
    note: str = "",
) -> dict[str, Any]:
    uid_s = sanitize_uid(target_uid)
    if not uid_s:
        raise ValueError("bad_uid")
    d = (decision or "").strip().lower()
    if d in ("allow", "allowed", "approve", "approved"):
        new_st = STATUS_ALLOWED
    elif d in ("deny", "denied", "reject", "rejected"):
        new_st = STATUS_DENIED
    else:
        raise ValueError("bad_decision")

    # WHY: decide against fresh accounts pull so we do not clobber remote status
    refresh_access_gate_from_gcs()
    now = int(time.time())
    with _LOCK:
        store = _read_accounts()
        row = store["users"].get(uid_s)
        if not isinstance(row, dict):
            raise ValueError("user_not_found")
        acc = _access_blob(row)
        acc["status"] = new_st
        acc["decided_at"] = now
        acc["decided_by"] = sanitize_uid(admin_uid) or (admin_email or "")[:120]
        acc["note"] = (note or "")[:300]
        row["access"] = acc
        store["users"][uid_s] = row
        _write_accounts(store)
        email = str(row.get("email") or "")

    append_event(
        {
            "type": f"access_{new_st}",
            "uid": uid_s,
            "email": email,
            "admin": admin_email,
            "message": note or new_st,
        }
    )
    return public_access_view(uid_s, email=email)


def user_may_use_paid(
    uid: str | None,
    *,
    email: str = "",
    is_admin: bool = False,
) -> bool:
    if not access_gate_enabled():
        return True
    if is_admin:
        return True
    # WHY: Allow on another instance must take effect before paid API (design/69)
    refresh_access_gate_from_gcs()
    st = str(get_access_for_uid(uid).get("status") or STATUS_NONE)
    return st in PAID_STATUSES
