"""
design/205 — TTS lexicons (acronyms, chem grapheme aliases).
"""

from __future__ import annotations

# Whole formula → conventional name. Longest key wins (CH3COOH before CO2).
CHEM_ALIASES: dict[str, str] = {
    "CH3COOH": "acetic acid",
    "CH3CO2H": "acetic acid",
    "C2H5OH": "ethanol",
    "CH3OH": "methanol",
    "H2SO4": "sulfuric acid",
    "H2O2": "hydrogen peroxide",
    "NaOH": "sodium hydroxide",
    "H2O": "water",
    "H\u2082O": "water",
    "CO2": "carbon dioxide",
    "CO\u2082": "carbon dioxide",
    "CH4": "methane",
    "CH\u2084": "methane",
    "NH3": "ammonia",
    "NH\u2083": "ammonia",
    "HCl": "hydrochloric acid",
    "NO2": "nitrogen dioxide",
    "NO\u2082": "nitrogen dioxide",
    "SO2": "sulfur dioxide",
    "SO\u2082": "sulfur dioxide",
    "CO": "carbon monoxide",
    "O2": "oxygen",
    "O\u2082": "oxygen",
    "N2": "nitrogen",
    "N\u2082": "nitrogen",
    "H2": "hydrogen",
    "H\u2082": "hydrogen",
}

# Pieces inside a larger formula, after the whole-token name missed.
FORMULA_FRAGMENTS: dict[str, str] = {
    "COOH": "carboxyl",
    "CO2H": "carboxyl",
    "C2H5": "ethyl",
    "CH3": "methyl",
    "NH2": "amino",
    "NO2": "nitro",
    "OH": "hydroxy",
    "Ph": "phenyl",
}

ACRONYM_SPOKEN: dict[str, str] = {
    "NMR": "n m r",
    "XRD": "x r d",
    "XPS": "x p s",
    "FT": "f t",
    "FTIR": "f t i r",
    "FT-IR": "f t i r",
    "FT–IR": "f t i r",
    "ATR": "a t r",
    "SEM": "s e m",
    "TEM": "t e m",
    "STEM": "s t e m",
    "AFM": "a f m",
    "STM": "s t m",
    "EDS": "e d s",
    "EDX": "e d x",
    "EELS": "e e l s",
    "DFT": "density functional theory",
    "GC": "g c",
    "MS": "mass spectrometry",
    "GCMS": "g c m s",
    "HPLC": "h p l c",
    "BET": "b e t",
    "TGA": "t g a",
    "DSC": "d s c",
    "UV": "u v",
    "IR": "i r",
    "MOF": "m o f",
    "COF": "c o f",
    "HER": "h e r",
    "OER": "o e r",
    "ORR": "o r r",
    "CV": "cyclic voltammetry",
    "EIS": "e i s",
    "PDF": "p d f",
    "NASA": "nasa",
    "MALDI": "maldi",
    "CVD": "c v d",
    "ALD": "a l d",
    "PVD": "p v d",
    "PECVD": "p e c v d",
    "MOCVD": "m o c v d",
    "SI": "supporting information",
    "eq.": "equation",
    "Eq.": "equation",
    "fig.": "figure",
    "Fig.": "figure",
    # design/339 — `Figs.` was left alone and TTS said "figs", the fruit.
    "figs.": "figures",
    "Figs.": "figures",
    "eqs.": "equations",
    "Eqs.": "equations",
    "et al.": "et al",
    "i.e.": "that is",
    "e.g.": "for example",
    "vs.": "versus",
    "cf.": "compare",
}

ACRONYM_NAME_HINTS: dict[str, tuple[str, ...]] = {
    "NMR": ("nuclear magnetic resonance",),
    "XRD": ("x-ray diffraction", "x ray diffraction"),
    "XPS": ("x-ray photoelectron", "x ray photoelectron"),
    "FTIR": ("fourier transform infrared", "ft-ir", "ft ir"),
    "SEM": ("scanning electron",),
    "TEM": ("transmission electron",),
    "DFT": ("density functional",),
    "HPLC": ("high-performance liquid", "high performance liquid"),
    "BET": ("brunauer", "emmett", "teller"),
    "TGA": ("thermogravimetric",),
    "DSC": ("differential scanning calorimetry",),
    "MOF": ("metal-organic framework", "metal organic framework"),
    "HER": ("hydrogen evolution",),
    "OER": ("oxygen evolution",),
    "ORR": ("oxygen reduction",),
    "EIS": ("electrochemical impedance",),
    "MS": ("mass spectrometry", "mass spectroscopy"),
}
