"""
design/205 — TTS lexicons (acronyms, chem grapheme aliases).
"""

from __future__ import annotations

# Exact grapheme -> spoken (before plain chem digits).
CHEM_ALIASES: dict[str, str] = {
    "H2O": "H two O",
    "H\u2082O": "H two O",
    "CO2": "C O two",
    "CO\u2082": "C O two",
    "CH4": "C H four",
    "CH\u2084": "C H four",
    "O2": "O two",
    "O\u2082": "O two",
    "N2": "N two",
    "N\u2082": "N two",
    "NH3": "N H three",
    "NH\u2083": "N H three",
    "NO2": "N O two",
    "NO\u2082": "N O two",
    "SO2": "S O two",
    "SO\u2082": "S O two",
    "H2": "H two",
    "H\u2082": "H two",
}

ACRONYM_SPOKEN: dict[str, str] = {
    "NMR": "n m r",
    "XRD": "x r d",
    "XPS": "x p s",
    "FTIR": "f t i r",
    "ATR": "a t r",
    "SEM": "s e m",
    "TEM": "t e m",
    "STEM": "s t e m",
    "AFM": "a f m",
    "STM": "s t m",
    "EDS": "e d s",
    "EDX": "e d x",
    "EELS": "e e l s",
    "DFT": "density functional theory",
    "GC": "g c",
    "MS": "mass spectrometry",
    "GCMS": "g c m s",
    "HPLC": "h p l c",
    "BET": "b e t",
    "TGA": "t g a",
    "DSC": "d s c",
    "UV": "u v",
    "IR": "i r",
    "MOF": "m o f",
    "COF": "c o f",
    "HER": "h e r",
    "OER": "o e r",
    "ORR": "o r r",
    "CV": "cyclic voltammetry",
    "EIS": "e i s",
    "PDF": "p d f",
    "SI": "supporting information",
    "eq.": "equation",
    "Eq.": "equation",
    "fig.": "figure",
    "Fig.": "figure",
    "et al.": "et al",
    "i.e.": "that is",
    "e.g.": "for example",
    "vs.": "versus",
    "cf.": "compare",
}

ACRONYM_NAME_HINTS: dict[str, tuple[str, ...]] = {
    "NMR": ("nuclear magnetic resonance",),
    "XRD": ("x-ray diffraction", "x ray diffraction"),
    "XPS": ("x-ray photoelectron", "x ray photoelectron"),
    "FTIR": ("fourier transform infrared", "ft-ir", "ft ir"),
    "SEM": ("scanning electron",),
    "TEM": ("transmission electron",),
    "DFT": ("density functional",),
    "HPLC": ("high-performance liquid", "high performance liquid"),
    "BET": ("brunauer", "emmett", "teller"),
    "TGA": ("thermogravimetric",),
    "DSC": ("differential scanning calorimetry",),
    "MOF": ("metal-organic framework", "metal organic framework"),
    "HER": ("hydrogen evolution",),
    "OER": ("oxygen evolution",),
    "ORR": ("oxygen reduction",),
    "EIS": ("electrochemical impedance",),
    "MS": ("mass spectrometry", "mass spectroscopy"),
}
